### ISSUE TITLE
Allowing access on QBaikal server

### ISSUE THREAD

**Issue by Superwallah** [mrbaseman/calendar-tools#3]
Hi,

I am trying to use your script on a QNAP NAS with the QBaikal package http://forum.qnap.com/viewtopic.php?f=320&t=109451&hilit=qbaikal 

I am asked for a username and password for "My Realm". But the admin password of the NAS does not work.
Where do I set the access control? On file system level?

**Comment by mrbaseman** [comment]
did you place the script in the admin-directory? at least for Baikal
0.2.7 it should then find the credentials for the baikal admin login. It
might be that the qnap package is somehow a modified version.

**Comment by Superwallah** [comment]
Yes. I have placed it under the admin directory:

`[/share/MD0_DATA/.qpkg/QBaikal/QBaikal/admin] # ls -al

drwxrwx---    3 admin    administ      4096 Feb 15 23:33 ./

drwxrwx---    7 admin    administ      4096 Feb 14 21:02 ../

-rwxrwx---    1 admin    administ      2697 Feb  3  2014 index.php*

drwxrwx---    2 admin    administ      4096 May 20  2015 install/

-rwxrwx---    1 admin    administ     16245 Mar 29  2015 permissions.php*
`
I address QBaikal via https://localNASname:31443/admin .

**Comment by Superwallah** [comment]
I have tried the Baikal admin password as well as the NAS admin password.

**Comment by Superwallah** [comment]
Anything else I can test? 
For debugging purposes, I adapted one line:
`die ("You" . $_SERVER['PHP_AUTH_USER'] . "are not allowed to see this page. Please authenticate.");
`
When clicking OK, the password box reappears. Clicking Cancel, gives
`Youare not allowed to see this page. Please authenticate.`

**Comment by mrbaseman** [comment]
it seems the webserver running on that box didn't authenticate you - or
is not configured to hand through the user to php. You could compare the
forked baikal version against the upstream version and see how that
differs in the authentication code. You might have to adapt the
permissions script the same way.

**Comment by Superwallah** [comment]
To check the access on http server level, I added a file test.php to the same directory with the same file access rights and ownerships. It is accessible without authentication.
In which user base is Apache looking for user credentials when asking for "basic authentication"? Are these the users defined in /etc/passwd on system level or in its own database? How can I find out which user base is used in the QBaikal package?

**Comment by mrbaseman** [comment]
I managed to unpack the QBaikal-Package and it contains exactly what is
delivered as baikal-flat last stable version, and in addition an apache
configuration file. That apache config includes several other
qnap-specific configurations, but it also defines AccessFileName .htaccess
That's usually where you can set up local access rights in apache, (if
you want on the level of individual directories). Probably this is done
in the top directory, or in one of the configuration files that are
included here.
If you can't find it elsewhere, you could add a .htaccess file for the
admin directory. In each .htaccess file you can specify a .htpasswd file
(normally one tries to keep things simple and use a central .htaccess
file which is referenced by all .htaccess files). To generate the hashes
for the .htpasswd file you need the htpasswd utility. It might be
already installed on the qnap or you create the file on a linux host and
copy it from there. A nice tutorial how to set up password
authentication with apache is here:

https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04

Since I don't have a qnap, it's difficult for me to analyze what exactly
is happening in such an environment, but I hope this background
information helps you a bit to find the necessary steps for a working
configuration. My script just checks if the user admin is authenticated
in the current session.
One way might be authenticating with the baikal admin backend and let
that one establish the authenticated session - or you set up the
authentication directly with the apache configuration as described above
to make the web server deliver the necessary authentication information
to the permission script.
BTW: The password here must be the same as the baikal-admin password,
because my script compares the hash to the hash in Baikal's configuration.

PS.I was hoping to get some help (or find some time myself) to properly
integrate the script into the admin-backend, but that's still an open
issue, sorry.

**Comment by mrbaseman** [comment]
ah, now I see the problem. I'm doing exactly what I have described
yesterday evening:
I let the apache do basic authentication and so the client authenticates
with the web server.
Then I check again this authentication against the hash in the baikal
configuration.
I'll post an updated script which properly checks if the user is
authenticated against baikal.

**Comment by mrbaseman** [comment]
I have just updated permissions.php
There are three changes:
With basic authentication it uses the correct "realm",
It supports digest authentication now, depending on Baikals settings
which method to use,
It properly connects to Baikals php session (only if no valid session
exists, it asks for authentication).
Could you try this version on your qnap?

**Comment by Superwallah** [comment]
Great. Thanks.
1. It works now with Digest authentication.
2. It works without entering the password again after being logged in into the admin interface
3. As I learnt from one of your comments, admin password of the apache account and of Baikal have to be the same. I had this not like that when I first started checking out your script. And I still this that this might be worth an improvement. But I guess, this is not easy as you need some stored credential for comparison?!?
4. Accessing the permissions.php without logging into Baikal before is not possible. The authentication dialog won't accept my password .... as there is not Baikal session, I guess. But this is okay.

Having it now on this level, "integration" is easy. I just add a link (ugly  unformatted) to the admin page.

Thanks for helping out!!!

**Comment by mrbaseman** [comment]
- You don't need an apache account. The script would query for the baikal credentials. 
- My proposal to set up an apache account with the same credentials was just an attempt to get it working in your environment (where I don't know how the full apache configuration looks like).
- Maybe if you remove the .htaccess file you can log in by the script, now, because another constraint is that the authentication type for apache and baikal must match also. Otherwise the browser might re-send the credentials you have entered before to access the directory, and these (username, realm, type, password) do not match the ones you need for the script - or, if you are prompted for the credentials for the script, these might overwrite the ones you need to access the directory. 
- If you want to keep the additional password protection via .htaccess you can use different credentials as for baikal now, but if you do so, you have to authenticate with baikal first, and then call the permissions script (either by a link or in a separate tab of the same browser), because it can properly use the baikal session now and skips its own authentication procedure when a valid backend admin session is present. You can, however, not call the script directly then as explained in the previous paragraph.
